thrust_allocation_node:
  ros__parameters:
    publish_rate: 10.0 # Hz
    loop_rate: 100.0 # Hz
    min_force: -500
    
    maneuvering:
      gamma: 7.5 # 7.5 for power-based # 0.5 for normal
      mu: 10.0 # 10.0 for power-based
      rho: 10.0 # 10.0 for power-based
      zeta: 0.05
      rate_limit: 25.0 # 25.0 for power-based
      theta_min: -100.0
      theta_max: 100.0
      lambda: 0.0
      power_management: true

    qp:
      u_bound: 300.0
      max_rate: 1.0
      max_force_rate: 100.0
      beta: 1.1

    nlp:
      u_bound: 400.0
      w_angle: 1000.0
      w_neg: 10.0
      w_alpha_change: 50000.0
      max_rate: 0.5
